### PR TITLE
build(dev): add Docker infrastructure

### PR DESCRIPTION
**Pull request by eventualbuddha**
This commit adds the ability to develop module-smartcards using Docker as an alternative approach. This does not replace the existing approach, just makes a new one available.

The main advantages are reproducibility and isolation of development environment, ease of installing dependencies regardless of the host system, and ease of orchestrating development processes. The main disadvantages are adding indirection to development systems and adding reliance on yet more software (Docker).

### CODE REVIEW

**Comment by eventualbuddha** [comment]
Open question: how do we access real hardware with this?

**Comment by benadida** [comment]
> Open question: how do we access real hardware with this? [This SO post](https://stackoverflow.com/questions/24225647/docker-a-way-to-give-access-to-a-host-usb-or-serial-device) may contain answers.

If we can solve it, I like it. I'm thinking we should figure this out before we merge?

**Comment by eventualbuddha** [comment]
> I'm thinking we should figure this out before we merge?

Yes.

**Comment by eventualbuddha** [comment]
Merging after verbal okay from @benadida.

**Pull request merged**
